<?php
declare(strict_types = 1);

# This file is to be the first code executed for any incoming request. It sets
# up the autoloader and sanitises the environment.

# The vendor directory is generated by Composer. It contains the autoloader,
# which automatically loads source files containing class definitions when the
# class is first used. See the PHP documentation on autoloaders and PSR-4 for
# more information.
require_once __DIR__ . '/../vendor/autoload.php';

# Patch the obsolete error reporting mechanism so that exceptions are thrown
# instead. These exceptions are easier to handle. See the PHP documentation on
# ErrorException for more information.
\set_error_handler(function($severity, $message, $file, $line) {
    throw new \ErrorException($message, 0, $severity, $file, $line);
});
